spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sardine-system?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: HSJZxXx007
